[workspace]
members=[
    "ch3",
    "chapter1",
    "guessing_game",
    "homework_1",
    "chapter4",
    "homework_2",
    "chapter5",
    "chapter6",
    "chapter7",
    "backyard",
    "restaurant",
    "chapter8",
    "homework_4",
    "tokio",
]
