[package]
name = "chapter5"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "rectangles"
path = "src/rectangles.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
